### ISSUE TITLE
[Setting] Xcode 프로젝트 생성 및 .gitignore 세팅

### ISSUE THREAD

**Issue by lsj8706** [sopt-makers/SOPT-Notice-iOS#1]
## 💡 Issue

- Xcode 프로젝트 생성
- .gitignore 세팅

## 📝 To-do

- [ ] Xcode 프로젝트 생성
- [ ] iOS 최소 버전 14.0으로 설정
- [ ] identifier는 com.sopt-makers.release
- [ ] .gitignore 파일 생성하고 내용 추가
