### ISSUE TITLE
[Feat] APNS 기본 세팅

### ISSUE THREAD

**Issue by yangsubinn** [sopt-makers/SOPT-Notice-iOS#35]
## 💡 Issue

푸시알림 기본 세팅

## 📝 To-do

- [x] push notification, background mode 활성화
- [x] APNS 설정, 등록
- [x] 가능하면 푸시 알림 테스트 앱으로 테스트까지
https://github.com/onmyway133/PushNotifications#opening-app-on-macos-catalina-1015
